apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.gmail: ayyarsachin@gmail.com
spec:
  destination:
    namespace: pipeline-demo
    server: https://api.cluster-cnh84.cnh84.sandbox758.opentlc.com:6443
  project: default
  source:
    path: k8s
    repoURL: https://github.com/sachinayyar/tekton-spring-boot-config.git
    targetRevision: main
  syncPolicy:
    automated: {}
